apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: open-liberty-certified
  namespace: openshift-operators
spec:
  channel: beta2
  installPlanApproval: Automatic
  name: open-liberty-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: open-liberty-operator.v0.8.0
