# https://github.com/orgs/community/discussions/47165
name: Debug with tmate
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ALLSECRETS: "${{ toJSON(secrets) }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 10
